package com.anxiuze.po.user;

public class NbaUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_user.id
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_user.user_name
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_user.user_age
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    private Integer userAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nba_user.address
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_user.id
     *
     * @return the value of nba_user.id
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_user.id
     *
     * @param id the value for nba_user.id
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_user.user_name
     *
     * @return the value of nba_user.user_name
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_user.user_name
     *
     * @param userName the value for nba_user.user_name
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_user.user_age
     *
     * @return the value of nba_user.user_age
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public Integer getUserAge() {
        return userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_user.user_age
     *
     * @param userAge the value for nba_user.user_age
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public void setUserAge(Integer userAge) {
        this.userAge = userAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nba_user.address
     *
     * @return the value of nba_user.address
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nba_user.address
     *
     * @param address the value for nba_user.address
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}