package com.anxiuze.dao;

import com.anxiuze.po.user.NbaUser;
import com.anxiuze.po.user.NbaUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface NbaUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int countByExample(NbaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int deleteByExample(NbaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int insert(NbaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int insertSelective(NbaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    List<NbaUser> selectByExample(NbaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    NbaUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") NbaUser record, @Param("example") NbaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int updateByExample(@Param("record") NbaUser record, @Param("example") NbaUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int updateByPrimaryKeySelective(NbaUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table nba_user
     *
     * @mbggenerated Tue Jul 07 23:43:50 CST 2020
     */
    int updateByPrimaryKey(NbaUser record);
}